# Generated by Django 4.1.3 on 2022-12-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
