# Generated by Django 4.1.3 on 2022-12-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_profile_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostFollowing',
        ),
        migrations.DeleteModel(
            name='UpdatePost',
        ),
        migrations.AlterField(
            model_name='post',
            name='Inbox',
            field=models.TextField(max_length=300),
        ),
    ]
