# Generated by Django 4.1.3 on 2022-12-14 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_delete_postfollowing_delete_updatepost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Joined',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bio', models.CharField(blank=True, max_length=160, null=True)),
                ('Location', models.CharField(blank=True, max_length=30, null=True)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
