# Generated by Django 4.1.3 on 2022-12-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_profile_joined_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Joined',
        ),
    ]
