# Generated by Django 4.1.3 on 2022-12-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_profile_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
