# Generated by Django 4.1.3 on 2022-12-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_profile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Background_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
