# Generated by Django 4.1.3 on 2022-12-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_profile_background_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
