# Generated by Django 4.1.3 on 2022-12-15 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_profile_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
