# Generated by Django 4.1.3 on 2022-12-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_profile_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Born',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='profile',
            name='Occupation',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='profile',
            name='Status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Complicated', 'Complicated'), ('In a Relationship', 'In a Relationship')], max_length=160),
        ),
    ]
