# Generated by Django 4.1.3 on 2022-12-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_profile_born_profile_occupation_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ("It's Complicated", "It's Complicated"), ('In a Relationship', 'In a Relationship')], max_length=160),
        ),
    ]
