# Generated by Django 4.1.3 on 2022-12-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
