# Generated by Django 4.1.3 on 2022-12-18 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_alter_profile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
