# Generated by Django 4.1.3 on 2022-12-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_alter_profile_born'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Born',
            field=models.DateField(blank=True, max_length=160),
        ),
    ]
