# Generated by Django 4.1.3 on 2022-12-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_alter_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
